name: AlleyPractice
version: '${project.version}'
main: us.alleypvp.practice.AlleyPractice
author: Hamza, Remi & Emmy (ysubz edit)
description: '${project.description}'
softDepend:
  - PlaceholderAPI
  - SlimeWorldManager
depend: [ FastAsyncWorldEdit, WorldEdit ]
