name: KaosPractice
version: '${project.version}'
main: com.kaosmc.practice.KaosPractice
authors: ysubz
description: '${project.description}'
website: https://knowplugins.com
softDepend:
  - PlaceholderAPI
depend: [ FastAsyncWorldEdit, WorldEdit ]