name: KaosPractice
version: '${project.version}'
main: com.kaosmc.practice.KaosPractice
author: ysubz
description: '${project.description}'
website: https://kaosmc.com
softDepend:
  - PlaceholderAPI
  - SlimeWorldManager
depend: [ FastAsyncWorldEdit, WorldEdit ]
