plugin:
  # Define se o Kaos Practice deve atualizar automaticamente ao iniciar o servidor, quando houver nova versão.
  auto-update: false

arena-management:
  swm:
    # Ativa o gerenciamento de arenas standalone via SlimeWorldManager.
    enabled: true
    # Loader registrado no SWM (ex.: file, mysql, mongodb...).
    loader: mongodb

crafting-operations:
  blocked-items: [ ]

commands:
  anti-syntax-message: '&cVocê não pode executar {argument}.'
  # Este comando é executado sempre que um jogador compra um item cosmético no menu da loja in-game.
  grant-cosmetic-permission: permission set {player} {permission}

configuration:
  arena-default-display-name:
    # Ao criar uma arena, estes são os valores padrão que serão aplicados.
    ffa: '&6{arena-name}'
    shared: '&6{arena-name}'
    standalone: '&6{arena-name}'
  default-kit-values:
    # Ao criar um kit, estes são os valores padrão que serão aplicados.
    description: ''
    disclaimer: '&7Aviso do kit {kit-name}.'
    display-name: '&6{kit-name}'
    menu-title: '&6&l{kit-name}'

explosive:
  # Define se você quer usar as mecânicas de explosivos nativas do Kaos (Fireball e TNT instantânea).
  enabled: true
  values:
    fireball:
      # Raio afetado da explosão, em blocos.
      explosion-range: 3.0
      # Multiplicador de knockback horizontal aplicado nas entidades atingidas pela explosão.
      horizontal-kb: 2.5
      # Velocidade com que a fireball é lançada.
      throw-speed: 0.7
      # Multiplicador de knockback vertical aplicado nas entidades atingidas pela explosão.
      vertical-kb: 2.2
    tnt:
      # Raio afetado da explosão, em blocos.
      explosion-range: 3.0
      # Tempo do pavio em ticks antes da TNT explodir.
      fuse-ticks: 60

game:
  # Raio do portal do End que atuará como objetivo (não altere sem saber o que está fazendo).
  portal-radius: 5
  # Comandos bloqueados durante partidas.
  blocked-commands:
    - kill
    - tp
  # Quantidade de vidas que cada jogador terá (ex.: PearlFight).
  lives-per-game: 3

permissions:
  syntax-bypass-permission: kaos.syntax.bypass
  color-code-usage-permission: kaos.chat.color
  donators:
    # Permite que jogadores escolham arena em parties.
    party-arena-selector: kaospractice.duel.arena.selector
    # Permite que jogadores escolham arena no menu /duel.
    duel-arena-selector: kaospractice.duel.arena.selector
    # Permite voar no lobby/fila.
    lobby-flight-bypass: kaoscore.vip.fly
    # Permite usar emojis no chat (:sad:, etc).
    emoji-usage-permission: kaoscore.vip.emojis

practice-api:
  nametag:
    priority: 100

server:
  chat-format:
    global:
      enabled: false
      format: '&7[{nivel}&7]&r {prefix}{rank-color}{name-color}{player}{suffix}{tag}{separator}{message}'
      separator: '&7: &f'
    tag-appearance:
      format: ' {tag-color}{tag-prefix}'
    party:
      format: '§7[§6Party§7] {tag_prefix}{nick} §8» §f{message}'
  essentials:
    emoji-feature: true
  locations:
    spawn: world:10.0:100.0:100.0:0.0:0.0

sounds:
  match:
    platform-decay-notifications:
      '50':
        enabled: true
        value: WITHER_HURT
      '25':
        enabled: true
        value: ENDERDRAGON_GROWL
      '75':
        enabled: true
        value: DIG_STONE
